language: csharp
solution: SimpleAlphaVantage.sln
mono: none
dotnet: 2.1
env:
  - TEST_FILE_BASE=SimpleAlphaVantageTests/ResponseTests/TestData
install:
  - dotnet restore
  #- nuget install NUnit.Console -Version 3.8.0 -OutputDirectory testrunner
  - mkdir -p $TEST_FILE_BASE && tar xf $TEST_FILE_BASE.tar.gz -C $TEST_FILE_BASE
script:
  - ls /home/travis/build/Eibwen/SimpleAlphaVantage/SimpleAlphaVantageTests/bin/Release/netcoreapp2.0
  - ls /home/travis/build/Eibwen/SimpleAlphaVantage/SimpleAlphaVantageTests/bin/Release/netcoreapp2.0/SimpleAlphaVantageTests/ResponseTests
  - ls /home/travis/build/Eibwen/SimpleAlphaVantage/SimpleAlphaVantageTests/bin/Release/netcoreapp2.0/SimpleAlphaVantageTests/ResponseTests/TestData
  #- dotnet build
  #- mono ./testrunner/NUnit.ConsoleRunner.3.8.0/tools/nunit3-console.exe ./SimpleAlphaVantageTests/bin/Release/netstandard2.0/SimpleAlphaVantageTests.dll
  - dotnet test SimpleAlphaVantageTests -c Release
  - dotnet pack SimpleAlphaVantage -c Release
  - echo $TRAVIS_COMMIT -- $TRAVIS_PULL_REQUEST_SHA -- $TRAVIS_COMMIT_RANGE -- $TRAVIS_BRANCH
  #- echo ${TRAVIS_COMMIT:0:8} -- end chars- ${TRAVIS_COMMIT:(-8)} -- `echo $TRAVIS_COMMIT | cut -c1-8`
  #- echo no suffix if master- $([ "$TRAVIS_BRANCH" == "master" ] && echo "" || echo "--version-suffix \"$TRAVIS_BRANCH\"")
  - echo SimpleAlphaVantage -c Release /p:PackageVersion=1.0.1.$TRAVIS_BUILD_ID /p:PackageReleaseNotes=${TRAVIS_COMMIT:0:8} $([ "$TRAVIS_BRANCH" == "master" ] && echo "" || echo "--version-suffix \"$TRAVIS_BRANCH\"")
  - dotnet pack SimpleAlphaVantage -c Release /p:PackageVersion=1.0.1.$TRAVIS_BUILD_ID /p:PackageReleaseNotes=${TRAVIS_COMMIT:0:8} $([ "$TRAVIS_BRANCH" == "master" ] && echo "" || echo "--version-suffix \"$TRAVIS_BRANCH\"")
after_success:
  - dotnet nuget push SimpleAlphaVantage/bin/Release/SimpleAlphaVantage.*.nupkg --api-key $NUGET_API_KEY
  